all:
	cd frame && make all
	cd region && make all
	cd smart_ptr && make all

clean:
	cd frame && make clean
	cd region && make clean
	cd smart_ptr && make clean

run:
	cd frame && make run
	cd region && make run
	cd smart_ptr && make run
